GET http://localhost:3001/users
content-type: application/json

###


GET http://localhost:3001/users
content-type: application/json 

###


POST http://localhost:3001/users
content-type: application/json

{
    "name": "mook",
    "country": "US",
    "photo": "none",
    "email": "Parisfexas",
    "artist": "The Chairs",
    "artistImage": "none",
    "genre": [],
    "topTrack": {}

}

###

DELETE http://localhost:3001/users/

###

PATCH http://localhost:3001/users/
content-type: application/json

{
    "name": "mort",
    "country": "Ukraine"
}
