GET http://localhost:3001/users
content-type: application/json

###


GET http://localhost:3001/users
content-type: application/json 

###


POST http://localhost:3001/users
content-type: application/json

{
    "name": "jjjoojioj",
    "country": "US",
    "photo": "none",
    "email": "ojiib",
    "artist": "The Chairs",
    "artistImage": "none",
    "genre": ["ff", "ff"],
    "topTrack": {}
}



###

DELETE http://localhost:3001/users/

###

PATCH http://localhost:3001/users
content-type: application/json

{
    "email": "jjj",
    "following": "me8789"
}


###
GET http://localhost:3001/inbox
content-type: application/json

###



POST http://localhost:3001/inbox
content-type: application/json

{
   "users": ["af8923", "sdfaj9"],
   "messages": ["hi", "whatsup"]
}



###
